// import { Inter } from 'next/font/google';
import { getAllClasses } from '@/lib/apiFunctions/classes';
import Head from 'next/head';

// const inter = Inter({ subsets: ['latin'] });

import styled from 'styled-components';

const TestContainer = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
`;

const ClassRow = styled.div`
  width: 100%;
  height: 20px;
  display: flex;
  justify-content: center;
  align-items: center;
`;

export default function Home({ classes }) {
  classes && console.log(classes);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={``}>
        <TestContainer>
          {classes && classes.results.map((cls, i) => <ClassRow key={i}>{cls.name}</ClassRow>)}
        </TestContainer>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const classes = await getAllClasses();
  console.log(classes);

  return {
    props: { classes: classes },
  };
}
