// import { Inter } from 'next/font/google';
import apiClient from '@/lib/apiFunctions/apiClient';
import { getAllClasses } from '@/lib/apiFunctions/classes';
import Head from 'next/head';

// const inter = Inter({ subsets: ['latin'] });

import styled from 'styled-components';

const TestContainer = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
  gap: 10px;
`;

const ClassRow = styled.div`
  width: 200px;
  height: 40px;
  border: 1px solid #dadada;
  display: flex;
  justify-content: center;
  align-items: center;
  transition: all 150ms ease-in-out;
  cursor: pointer;
  :hover {
    background-color: #fafafa;
    box-shadow: 0px 0px 10px #dadada;
  }
`;

export default function Home({ classes }) {
  classes && console.log(classes);

  async function handleClick(cls) {
    await apiClient({
      url: `classes/${cls}`,
    }).then((res) => {
      alert(`This is the ${res.data.index} class. Proficiency choices: ${res.data.proficiency_choices[0].desc}  `);
    });
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={``}>
        <TestContainer>
          {classes &&
            classes.results.map((cls, i) => (
              <ClassRow onClick={() => handleClick(cls.index)} key={i}>
                {cls.name}
              </ClassRow>
            ))}
        </TestContainer>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const classes = await getAllClasses();
  console.log(classes);

  return {
    props: { classes: classes },
  };
}
